version: 2.1

references:
    container_config: &container_config
        docker:
            - image: circleci/android:api-28

        working_directory: ~/data

        environment:
            JVM_OPTS: -Xmx3g

jobs:

    ktlint:
        <<: *container_config
        steps:
            - checkout
            - run: ./gradlew ktlint

    detekt:
        <<: *container_config
        steps:
            - checkout
            - run: ./gradlew detekt

    lint:
        <<: *container_config
        steps:
            - checkout
            # pure "lint" gradle task should be avoided because it is parent task for lintDebug and lintRelease (it runs lint
            # multiple times for each build variant). We want to run "lintDebug" task, because it's faster.
            - run: ./gradlew lintDebug

    build_app:
        description: An executor with sensible defaults for Android Gradle tasks (set with GRADLE_OPTS).

        <<: *container_config

        environment:
            GRADLE_OPTS: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

        steps:
            - checkout
            - run: ./gradlew :app:bundleDebug
workflows:
    version: 2
    check:
        jobs:
            - lint
            - detekt
            - ktlint