version: 2
jobs:
    build:
        docker:
            -   image: circleci/android:api-28

        working_directory: ~/data

        environment:
            JVM_OPTS: -Xmx3g

        steps:
            - checkout
            -   restore_cache:
                    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

            -   run:
                    name: Chmod permissions
                    command: sudo chmod +x ./gradlew

            -   run:
                    name: Download dependencies
                    command: ./gradlew androidDependencies

            -   save_cache:
                    paths:
                        - ~/.gradle
                    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

            -   run:
                    name: Ktlint
                    command: ./gradlew ktlint

            -   run:
                    name: Detekt
                    command: ./gradlew detekt

            -   run:
                    name: Checkstyle
                    command: ./gradlew checkstyle

            -   store_artifacts:
                    path: app/build/reports
                    destination: reports

    deploy:

        filters:
            tags:
                only: /^t.*$/
            branches:
                ignore:
                    - /.*/
                    - master

        steps:
            - checkout

            -   restore_cache:
                    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

            -   run:
                    name: Chmod permissions
                    command: sudo chmod +x ./gradlew

            -   run:
                    name: Download dependencies
                    command: ./gradlew androidDependencies

            -   save_cache:
                    paths:
                        - ~/.gradle
                    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}


            -   run:
                    name: Assemble ReleaseQa
                    command: ./gradlew assembleReleaseQa

            -   run:
                    name: Upload ReleaseQa
                    command: ./gradlew appDistributionUploadReleaseQa

            -   store_artifacts:
                    path: app/build/outputs/apk/releaseQa
                    destination: apk
workflows:
    version: 2

    build_and_deploy_qa:
        jobs:
            - build
            - deploy:
                  requires:
                      - build