version: 2.1

references:
    container_config: &container_config
    docker:
        - image: circleci/android:api-28

    working_directory: ~/data

    environment:
        JVM_OPTS: -Xmx3g

jobs:
    restore_cache:
        <<: *container_config
        steps:
            - checkout
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    chmod_permissions:
        <<: *container_config
        command: sudo chmod +x ./gradlew

    download_dependencies:
        <<: *container_config
        command: ./gradlew androidDependencies

    save_cache:
        <<: *container_config
        paths:
            - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    ktlint:
        <<: *container_config
        command: ./gradlew ktlint

    detekt:
        <<: *container_config
        command: ./gradlew detekt

    checkstyle:
        <<: *container_config
        command: ./gradlew checkstyle

    save_reports:
        <<: *container_config
        path: app/build/reports
        destination: reports

workflows:
    version: 2
    quality:
        jobs:
            - restore_cache
            - chmod_permissions
            - download_dependencies
            - save_cache
            - ktlint
            - detekt
            - checkstyle
            - save_reports