name: DeployTest

on:
  push:
    tags:
      - v1.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Chmod permissions
      run: sudo chmod +x ./gradlew

    - name: Decode google-services.json
      env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > app/google-services.json

    - name: Build release Qa
      run: ./gradlew assembleReleaseQa

    - name: Upload artifact to Firebase App Distribution
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: ./gradlew appDistributionUploadReleaseQa

    - uses: actions/upload-artifact@v2
      with:
        name: Save apk
        path: app/build/outputs/apk/releaseQa/app-releaseQa.apk
